repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.14.5
    hooks:
      - id: typos
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
  - repo: local
    hooks:
      - id: completions
        name: Check completions up to date
        entry: bash scripts/check-completions.sh
        language: system
        pass_filenames: false
        files: ^protonup-rs/src/cli\.rs$
      - id: man-page
        name: Generate man page
        entry: bash scripts/go-md2man.sh
        language: system
        files: ^protonup-rs/man/protonup-rs\.1\.md$
