name: Lint

on:
  pull_request:

permissions: read-all

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Clippy Check
        uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d # v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  spell_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Writes changes in the local checkout
        uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f #v1.49.0
        with:
          write_changes: true
